AllCops:
  EnabledByDefault: true
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Style/HashSyntax:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Metrics/AbcSize:
  Enabled: false



